language: python
sudo: required
dist: trusty
python:
  - "3.4"
  - "3.5"
before_script:
  - curl -LO http://last.cbrc.jp/last-658.zip
  - unzip last-658.zip
  - pushd last-658 && make && sudo make install && popd
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y emboss parallel
# command to install dependencies
install:
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test python=$TRAVIS_PYTHON_VERSION numpy scipy pandas=0.17.0 matplotlib pytest pytest-cov coverage sphinx nose
  - source activate test
  - pip install -U codecov
  - python setup.py install
# command to run tests
script: py.test --pyargs shmlast --cov=./
after_success: codecov --token=9f900c67-c5a8-4adc-a110-53ef2b41f224
