name: py3.test.shmlast
dependencies:
- cairo=1.12.18=6
- cycler=0.10.0=py35_0
- dbus=1.10.10=0
- expat=2.1.0=0
- fontconfig=2.11.1=6
- freetype=2.5.5=1
- glib=2.43.0=1
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=0
- harfbuzz=0.9.39=1
- icu=54.1=0
- jpeg=8d=2
- libffi=3.2.1=0
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- libpng=1.6.22=0
- libxcb=1.12=1
- libxml2=2.9.2=0
- matplotlib=1.5.1=np111py35_0
- mkl=11.3.3=0
- numpy=1.11.2=py35_0
- openssl=1.0.2j=0
- pandas=0.19.0=np111py35_0
- pango=1.39.0=1
- pip=8.1.2=py35_0
- pixman=0.32.6=0
- pyparsing=2.1.4=py35_0
- pyqt=4.11.4=py35_4
- python=3.5.2=0
- python-dateutil=2.5.3=py35_0
- pytz=2016.7=py35_0
- qt=4.8.7=4
- readline=6.2=2
- scipy=0.18.1=np111py35_0
- seaborn=0.7.1=py35_0
- setuptools=27.2.0=py35_0
- sip=4.18=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.2.2=0
- zlib=1.2.8=3
- pip:
  - bz2file==0.98
  - cloudpickle==0.2.1
  - doit==0.29.0
  - ficus==0.3.2
  - filelock==2.0.6
  - nose==1.3.7
  - nose-capturestderr==1.2
  - py==1.4.31
  - pyinotify==0.9.6
  - pytest==3.0.3
  - screed==0.9
  - shmlast==1.0

